#.
#The Tank Capacity of the Disenchanter
#[@cui:RequiresReload:server]
#Range: > 0
disenchanterTankCapacity = 1000
#.
#The Tank Capacity of the Copier
#[@cui:RequiresReload:server]
#Range: > 0
copierTankCapacity = 4000
#.
#The Tank Capacity of the Blaze Enchanter
#[@cui:RequiresReload:server]
#Range: > 0
blazeEnchanterTankCapacity = 2000
#.
#The Maximum Extended Levels beyond Enchantment's Max Level that can be reached through Hyper-Enchanting
#Range: > 0
maxHyperEnchantingLevelExtension = 2
#.
#The Chance of whether Deployer-killed entities will drop Nugget of Experience
#Range: 0.0 ~ 1.0
deployerXpDropChance = 1.0
#.
enableHyperEnchant = false

