
[Armor]

	[Armor."Set Option"]
		#How many pieces of Gold Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerGoldArmorRequireSet = 4
		#How many pieces of Fire Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerFireArmorRequireSet = 4
		#How many pieces of Ender Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerEnderArmorRequireSet = 4
		#How many pieces of Water Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerWaterArmorRequireSet = 4
		#How many pieces of Wither Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerWitherArmorRequireSet = 4
		#How many pieces of Poison Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerPoisonArmorRequireSet = 4
		#How many pieces of Phantom Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerPhantomArmorRequireSet = 4
		#How many pieces of Feather Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerFeatherArmorRequireSet = 4
		#How many pieces of Echo Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerEchoArmorRequireSet = 4

[Effect]

	[Effect.Gold]

		[Effect.Gold.Armor]
			#Enable Gold Upgraded Armor Effect : Piglin become neutral ?
			EnablePiglinNeutral = true
			#Enable Gold Upgraded Armor Effect : Increase Luck ?
			EnableLuckBonus = true
			#How much is the luck bonus increased ?
			#Range: 1 ~ 99
			LuckBonus = 1

		[Effect.Gold."Tool&Weapon"]
			#Enable Gold Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusGoldWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusGoldWeapon = 10
			#Enable Gold Upgraded Weapon Effect : Increase Looting ?
			EnableLootingBonus = true
			#How much is the looting bonus increased ?
			#Range: 1 ~ 99
			LootingBonus = 1
			#How much is the looting bonus increased if enchanted ?
			#Range: 1 ~ 99
			LootingEnchantBonus = 1
			#Enable Gold Upgraded Weapon Effect : Increase Fortune ?
			EnableFortuneBonus = true
			#How much is the fortune bonus increased ?
			#Range: 1 ~ 99
			FortuneBonus = 1
			#How much is the fortune bonus increased if enchanted ?
			#Range: 1 ~ 99
			FortuneEnchantBonus = 1

	[Effect.Fire]

		[Effect.Fire.Armor]
			#Enable Fire Upgraded Armor Effect : Fire damage immune ?
			EnableFireImmune = true
			#Enable Fire Upgraded Armor Effect : Lava Speed ?
			EnableLavaSpeed = false

			[Effect.Fire.Armor.Durability]
				#Fire Upgraded Armor loose durability when protect the player ? (Require EnableFireImmune = True)
				EnableDamageDurabilityFireArmor = true
				#How many tick between durability damage for the Fire Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityFireArmor = 40
				#How many durability damage take the Fire Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityFireArmor = 1

		[Effect.Fire."Tool&Weapon"]
			#Enable Fire Upgraded Tool&Weapon Effect : Auto-Smelt ?
			EnableAutoSmelt = false
			#Auto-Smelt is affected by Fortune ? (Only Ingot & Charcoal)
			EnableAutoSmeltFortune = false
			#Enable Fire Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusFireWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusFireWeapon = 4
			#By how much are the damages increased in percentage if enchanted ?
			#Range: 1 ~ 999
			DamageBonusFireEnchantWeapon = 3

	[Effect.Ender]

		[Effect.Ender.Armor]
			#Enable Ender Upgraded Armor Effect : Saves from the void ?
			EnableVoidSave = true
			#Enable Ender Upgraded Armor Effect : Prevent Enderman Anger ?
			EnablePreventAnger = false

			[Effect.Ender.Armor.Durability]
				#Ender Upgraded Armor Break when save the player ? 
				EnableBreakEnderArmor = false

		[Effect.Ender."Tool&Weapon"]
			#Enable Ender Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusEnderWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusEnderWeapon = 4
			#Enable Ender Upgraded Weapon Effect : Prevent Teleport ?
			EnablePreventTeleport = true
			#Enable Ender Upgraded Weapon Effect : Double Looting against Enderman ?
			EnableDoubleLootingBonusEnderWeapon = false
			#Enable Ender Upgraded Weapon Effect : Teleports Loot ?
			EnableTeleportChest = true

	[Effect.Water]

		[Effect.Water.Armor]
			#Enable Water Upgraded Armor Effect : Water Breathing ?
			EnableWaterBreath = true
			#Enable Water Upgraded Armor Effect : Water Speed ?
			EnableWaterSpeed = true
			#Enable Water Upgraded Armor Effect : Mining Fatigue Immune ?(Only from the Elder Guardian and does not remove the effects already present)
			EnableElderGuardianDebuffImmune = false

			[Effect.Water.Armor.Durability]
				#Water Upgraded Armor loose durability when protect the player ? 
				EnableDamageDurabilityWaterArmor = true
				#How many tick between durability damage for the Water Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityWaterArmor = 40
				#How many durability damage take the Water Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityWaterArmor = 1

		[Effect.Water."Tool&Weapon"]
			#Enable Water Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusWaterWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusWaterWeapon = 10
			#Enable Water Upgraded Weapon Effect : Increase against Enderman Damage ?
			EnableDamageBonusWaterEndermanWeapon = true
			#By how much are the damages against increased Enderman in percentage ?
			#Range: 1 ~ 999
			DamageBonusWaterEndermanWeapon = 5
			#Enable Water Upgraded Tool Effect : Increase Mining Speed underwater ?
			EnableMiningSpeedUnderwater = true

	[Effect.Wither]

		[Effect.Wither.Armor]
			#Enable Wither Upgraded Armor Effect : Wither Immune ?
			EnableWitherImmune = true

			[Effect.Wither.Armor.Durability]
				#Wither Upgraded Armor loose durability when protect the player ? 
				EnableDamageDurabilityWitherArmor = true
				#How many tick between durability damage for the Wither Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityWitherArmor = 40
				#How many durability damage take the Wither Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityWitherArmor = 3

		[Effect.Wither."Tool&Weapon"]
			#Enable Wither Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusWitherWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusWitherWeapon = 4
			#Enable Wither Upgraded Weapon Effect : Wither Effect ?
			EnableWitherEffect = true

	[Effect.Poison]

		[Effect.Poison.Armor]
			#Enable Poison Upgraded Armor Effect : Poison Immune ?
			EnablePoisonImmune = true
			#Enable Poison Upgraded Armor Effect : Climbs Walls ?
			EnableClimbWall = true

			[Effect.Poison.Armor.Durability]
				#Poison Upgraded Armor loose durability when protect the player ? 
				EnableDamageDurabilityPoisonArmor = true
				#How many tick between durability damage for the Poison Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityPoisonArmor = 20
				#How many durability damage take the Poison Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityPoisonArmor = 5

		[Effect.Poison."Tool&Weapon"]
			#Enable Poison Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusPoisonWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusPoisonWeapon = 4
			#Enable Poison Upgraded Weapon Effect : Poison Effect ?
			EnablePoisonEffect = true

	[Effect.Phantom]

		[Effect.Phantom.Armor]
			#Enable Phantom Upgraded Armor Effect : Fall damage Immune ?
			EnableFallImmune = true
			#Enable Phantom Upgraded Armor Effect : Step Height ?
			EnableStepHeight = false

			[Effect.Phantom.Armor.Durability]
				#Phantom Upgraded Armor loose durability when protect the player ? (Depend on fall distance)
				EnableDamageDurabilityPhantomArmor = true
				#How many durability damage take the Phantom Upgraded Armor when protect the player ? (Fall distance * Value)
				#Range: 1 ~ 100
				MultiplierDamageDurabilityPhantomArmor = 1

		[Effect.Phantom."Tool&Weapon"]
			#Enable Phantom Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusPhantomWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusPhantomWeapon = 10
			#Enable Phantom Upgraded Tool Effect : Glowing Effect ?
			EnableGlowingEffect = false
			#Enable Phantom Upgraded Tool Effect : Reach ?
			EnableReachEffect = false
			#By how much are the reach increased ?
			#Range: 1 ~ 99
			BonusReachTool = 2

	[Effect.Feather]
		#Enable Feather Upgraded Tool Effect : Attracts Items ?
		EnableAttractItem = true

		[Effect.Feather.Armor]
			#Enable Feather Upgraded Armor Effect : Water & Lava Walking ?
			EnableWaterLavaWalking = false
			#Enable Feather Upgraded Armor Effect : Multi Jump ?
			EnableMultiJump = false
			#How many Multi Jump ?
			#Range: 1 ~ 99
			MultiJump = 2
			#Enable Feather Upgraded Armor Effect : Fall Damage Reduction ?
			EnableReduceFallDamage = true
			#Enable Feather Upgraded Armor Effect : Levitation Immune ?
			EnableLevitationImmune = true

			[Effect.Feather.Armor.Durability]
				#Feather Upgraded Armor loose durability when the player walk on water ? 
				EnableWaterDamageDurabilityFeatherArmor = false
				#Feather Upgraded Armor loose durability when the player walk on lava ? 
				EnableLavaDamageDurabilityFeatherArmor = false
				#Feather Upgraded Armor loose durability when reducing fall damage ? 
				EnableFallDamageDurabilityFeatherArmor = true
				#How many tick between durability damage for the Feather Upgraded Armor when the player walk on water/lava or slow falling ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityFeatherArmor = 20
				#How many durability damage take the Feather Upgraded Armor when the player walk on water/lava or slow falling ? 
				#Range: 1 ~ 100
				DamageDurabilityFeatherArmor = 1

	[Effect.Corrupt]

		[Effect.Corrupt.Armor]
			#Enable Corrupt Upgraded Armor Effect : Health Malus ?
			EnableHealthMalus = true
			#By how much are the health reduced in percentage ?
			#Range: 1 ~ 99
			HealthMalus = 10

		[Effect.Corrupt."Tool&Weapon"]
			#Enable Corrupt Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusCorruptWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusCorruptWeapon = 7
			#Enable Corrupt Upgraded Weapon Effect : Increase Looting ?
			EnableLootingBonusCorruptWeapon = true
			#How much is the looting bonus increased ?
			#Range: 1 ~ 99
			LootingBonusCorruptWeapon = 1
			#Enable Gold Upgraded Weapon Effect : Increase Fortune ?
			EnableFortuneBonusCorruptTool = true
			#How much is the fortune bonus increased ?
			#Range: 1 ~ 99
			FortuneBonusCorruptTool = 1

	[Effect.Echo]

		[Effect.Echo.Armor]
			#Enable Echo Upgraded Armor Effect : Soulbound
			EnableSoulbound = true
			#Enable Echo Upgraded Armor Effect : Possibility that items remain in the inventory upon death ?
			EnableKeepItemsChance = true
			#What are the chances that your items will remain in your inventory when you die?
			#Range: 1 ~ 100
			KeepItemsChance = 50
			#Enable Echo Upgraded Armor Effect : Reduce Damage ?
			EnableDamageBonusEchoArmor = true
			#By how much is the damage reduced in percentage ?
			#Range: 1 ~ 100
			DamageBonusEchoArmor = 50
			#Enable Echo Upgraded Armor Effect : Heals ?
			EnableHealEchoArmor = true
			#Delay between heals in seconds ?
			#Range: 1 ~ 999
			HealEchoArmorDelay = 30

		[Effect.Echo."Tool&Weapon"]
			#Enable Echo Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusEchoWeapon = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusEchoWeapon = 20
			#Enable Echo Upgraded Tool Effect : Exp Bonus ?
			EnableBonusExpEcho = true
			#How many exp minimum?
			#Range: 0 ~ 999
			MinExpEcho = 2
			#How many exp maximum?
			#Range: 0 ~ 999
			MaxExpEcho = 5

