
[items]

	[items.milk_bottles]
		#If milk can be inserted into cauldrons
		"Milk Cauldron" = true
		#If milkable mobs can be milked with empty glass bottles
		"Milking with Glass Bottles" = false
		#If cauldrons are filled with milk dropping from a dripstone
		"Milk from Dripstone" = true
		#If milkshakes can be inserted into cauldrons
		"Milkshake Cauldrons" = true

[blocks]

	[blocks.strawberry_bush]
		#The minimum height required for Strawberry Bushes to grow White Strawberries
		"White Strawberry minimum height" = 256
		#If arthropods that go through Strawberry Bushes are given Invisibility
		"Strawberry Bushes give arthropods Invisibility" = true

[mobs]

	[mobs.plantain_spider]
		"Plantain Spider spawn from Banana Bundles" = true
		"Plantain Spiders give Slipping" = true

	[mobs.chimpanzee]
		#The percentage chance for a Banana Plant to generate with a group of Chimpanzees
		"Chimpanzee group chance" = 0.25
		#The maximum amount of Chimpanzees that can spawn with a Banana Plant
		"Chimpanzee maximum group size" = 3
		#The minimum attempts for Chimpanzees to spawn with a Banana Plant
		"Chimpanzee minimum spawn attempts" = 12
		#The maximum attempts for Chimpanzees to spawn with a Banana Plant
		"Chimpanzee maximum spawn attempts" = 24

