
["Shield mechanics settings"]
	#List of shield items and their damage values. Start the game once to fill these entries with all modded shields automatically. Format: Shield name id;shield damage reduction on block; shield passive damage reduction when just held.E.g. default: ["minecraft:shield;65;15"] this give the minecraft shield 65% damage reduction on block, and 15% passive damage reduction when not blocking but held.To put multiple values seperate them by commas like this:  ["minecraft:shield;65;15", "minecraft:shield;65;15"] 
	shields = ["upgradednetherite:netherite_shield;75;12", "alexsmobs:shield_of_the_deep;66;17", "minecraft:shield;65;15", "upgradednetherite:corrupt_upgraded_netherite_shield;74;10", "upgradednetherite:phantom_upgraded_netherite_shield;66;18", "alexsmobs:skelewag_sword;68;11", "upgradednetherite:echo_upgraded_netherite_shield;72;14", "upgradednetherite:water_upgraded_netherite_shield;75;10", "upgradednetherite:poison_upgraded_netherite_shield;65;20", "upgradednetherite:wither_upgraded_netherite_shield;72;11", "artifacts:umbrella;50;10", "upgradednetherite:gold_upgraded_netherite_shield;72;13", "upgradednetherite:ender_upgraded_netherite_shield;71;14", "upgradednetherite:fire_upgraded_netherite_shield;66;18", "everythingcopper:copper_shield;64;12", "upgradednetherite:feather_upgraded_netherite_shield;74;12"]
	#Should the mechanic changes only affect players
	playerOnly = false
	#Should blocking with a shield set it on cooldown(players only), values are in ticks. 20 ticks = 1 sec
	#Range: 0 ~ 100
	blockCooldown = 5
	#Maximum percent of damage allowed to be blocked. Default:85
	#Range: 0 ~ 100
	maxblockdamagereduction = 85
	#Maximum percent of damage reduction while holding a shield(not blocking). Default:25
	#Range: 0 ~ 100
	maxpassivedamagereduction = 25

