#You can disable any mixin from Terra Incognita here.
#This WILL disable certain features of the mod, but can help if you are experiencing a mixin conflict with another mod.
#The key string is the mixin class name, relative to the base package, with slashes instead of dots.
#Example: azmalent.terraincognita.mixin.compat.quark.LanternBlockMixin -> compat/quark/LanternBlockMixin
#DON'T CHANGE ANYTHING IF YOU DON'T KNOW WHAT YOU ARE DOING!
"Terra Incognita Mixins" = {}

